((nil . ((fill-column . 70)
         (column-enforce-column . 70)
         (cider-default-cljs-repl . shadow)
         (cider-shadow-default-options . ":dev")
         (cider-shadow-cljs-global-options . "-A:dev:backend:frontend:test"))))
