version: "3.7"
services:
  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
