FROM flyway/flyway:6.3.2-alpine

COPY migrations /flyway/sql

ENTRYPOINT ["/bin/sh"]

CMD ["-c", "/flyway/flyway -url=jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate"]